# Generated by Django 5.0.6 on 2024-05-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='received_at',
            new_name='accepted_at',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='sent_at',
            new_name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='request_at',
        ),
        migrations.AddField(
            model_name='friends',
            name='request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
