# Generated by Django 5.0.6 on 2024-05-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_received_at_friends_accepted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='request_at',
            new_name='requested_at',
        ),
    ]
